### PR TITLE
:ghost: make code snippets optional in an incident

### PR DESCRIPTION
**Pull request by pranavgaikwad**

### CODE REVIEW

**Review by shawn-hurley — CHANGES_REQUESTED** [review]
I think that this line is still preventing the incidents to show up

https://github.com/konveyor/static-report/pull/112/files#diff-f478944e743bcba87baf8564958483df1ee362128f577ae0345cf083f7b20b9dR91

**Review by shawn-hurley — APPROVED** [review]
@ibolton336 @sjd78 can you look at this and see if we can bring it in?

**Review by ibolton336 — APPROVED** [review]
Screenshot 2024-06-13 at 12 05 10 PM


Tested and LGTM!

**Comment by ibolton336** [comment]
> @ibolton336 @sjd78 can you look at this and see if we can bring it in?

Tackle ui includes this change also:

https://github.com/konveyor/tackle2-ui/commit/10728adaaf7f817d684255027212f805cdf6decd

**Review by aufi — APPROVED** [review]
LGTM

**Pull request merged**
